apiVersion: v1
data:
  secretkey: aW9WbVhFUDFJbElVNW5pUGxYQTR2WTdyY1gyOGNYeUl6TEd3YURqTUppbmMwdEE3U1NrQ1l0VEpSUlpKL0V2Mgo5Tkd6djVtb2tXWGx3OXpJczVpMk1kbCs3Y1hGeFNMa0s3YUlhTzVCVHNpMnZXeitWd2xlNnErZVpNaEJzajRICmpQb3R2WlJSSFErVFBqTjJVK3dyV3lPMnZyZnhEM2ZReDNUMFp0YXF1ODA9
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
